kind: Service
apiVersion: v1
metadata:
  name: react-client
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 31000
  selector:
    app: nodejs-server
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: react-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-server
  template:
    metadata:
      labels:
        app: nodejs-server
    spec:
      containers:
        - name: react-client
          image: mishramayankk20/react_docker:123
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      restartPolicy: Always