apiVersion: v1
kind: Service
metadata:
  name: nodejs-server
spec:
  selector:
    app: nodejs-server
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: NodePort
---      
apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: nodejs-server 
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: nodejs-server 
  template: 
    metadata: 
      labels: 
        app: nodejs-server
    spec: 
      containers:
      - name: nodeimage
        image: mishramayankk20/nodejs_server:22
        ports: 
        - containerPort: 5000
    
